artifacts_root: artifacts

data_ingestion:
  rood_dir: artficats/data_ingestion
  source_URL: https://github.com/17manoj/Data_files/blob/main/Wine_quality.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion